services:
  api:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py sup &&
             python manage.py runserver 0.0.0.0:8000"

  client:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true 
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "3000:3000"