# Generated by Django 4.2.2 on 2023-06-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_members_alter_board_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='sabtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='sabtasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.task'),
        ),
    ]
