# Generated by Django 3.2.19 on 2023-07-12 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_alter_task_deadline_remove_task_sabtasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.column'),
        ),
    ]
