# Generated by Django 3.2.19 on 2023-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(),
        ),
    ]
